build:
  parallel: true
  project: SPASM.sln

environment:
  matrix:
  - platform: Win32
  - platform: x64
  - platform: mingw

build_script:
  - if NOT "%platform%"=="mingw" msbuild /p:Configuration=Debug
  - if NOT "%platform%"=="mingw" msbuild /p:Configuration=Release
  - if "%platform%"=="mingw" echo Working around non-existent strip for AppVeyor mingw...
  - if "%platform%"=="mingw" copy /b/v/y C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin\strip.exe C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin\i686-w64-mingw32-strip.exe
  - if "%platform%"=="mingw" set PATH=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin;%PATH%
  - if "%platform%"=="mingw" mingw32-make CROSS_COMPILE=i686-w64-mingw32- NO_APPSIGN=1

test_script:
  - if "%platform%"=="Win32" C:\Python35\python tests\test-runner.py Debug\SPASM.exe
  - if "%platform%"=="Win32" C:\Python35\python tests\test-runner.py Release\SPASM.exe
  - if "%platform%"=="x64" C:\Python35\python tests\test-runner.py x64\Debug\SPASM.exe
  - if "%platform%"=="x64" C:\Python35\python tests\test-runner.py x64\Release\SPASM.exe
  - if "%platform%"=="mingw" C:\Python35\python tests\test-runner.py SPASM.exe
